### ISSUE TITLE
Feature Request: Add link to GitHub Repo from the public website.

### ISSUE THREAD

**Issue by mattgauntseo-sentry** [getsentry/pypi#99]
It would be helpful for folks looking to find out where the internal pypi is configured.

**Comment by asottile-sentry** [comment]
there isn't a built-in way to do that with [dumb-pypi](https://github.com/chriskuehl/dumb-pypi)

**Comment by mattgauntseo-sentry** [comment]
I think I had a little look after raising this issue and came to the same conclusion, but was hoping you'd know of a trick. We could probably do something hacky(ish) to add it to the page, but it's not worth it IMO.
